getsentry/vroom

internal/occurrence/occurrence.go

This will create less issues overall.

ref: Remove transaction name from the fingerprint

---

CHANGELOG.md
cmd/vroom/config.go
cmd/vroom/main.go
go.mod
go.sum
scripts/run.sh

https://github.com/getsentry/ops/pull/6247

ref: Use environment variables for production config

---

internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go
internal/testutil/internal.go

Supports `is_application` for flamegraphs.

feat: handle is_application in flamegraph payload

---

go.mod
internal/sample/sample.go
internal/sample/sample_test.go
internal/testutil/testutil.go

Fixes https://github.com/getsentry/team-profiling/issues/93

fix: Remove meaningless unsymbolicated before main

---

internal/sample/sample.go

Revert "fix: Compare the value at the index in the stack, not the index itself"

---

internal/occurrence/detect_frame.go

Fixes https://github.com/getsentry/team-profiling/issues/227

chore: Change the duration threshold for Android occurrences

---

internal/occurrence/occurrence.go

Fixes https://github.com/getsentry/team-profiling/issues/228

ref: Remove sample count for Android occurrences

---

internal/occurrence/occurrence.go
internal/occurrence/occurrence_test.go

Fixes https://github.com/getsentry/team-profiling/issues/226

ref: Remove Android package names from methods for occurrences

---

internal/snubautil/functions.go

Path was unused and will be removed in the coming changes to suspect functions.

chore(profiling): Remove path from suspect functions

---

cmd/vroom/kafka.go
cmd/vroom/profile.go

This was mistakenly returning the full unpruned list.

fix(suspect-functions): Return pruned function list

---

cmd/vroom/kafka.go
internal/nodetree/nodetree.go

Reverts getsentry/vroom#247
This is increasing the cpu/memory/network for some reason. Rolling back to investigate.

Revert "feat(functions): New functions message"

---

cmd/vroom/kafka.go
internal/nodetree/nodetree.go

Reverts getsentry/vroom#253
Tested this again, looks to be some kind of transient issue during deploys. It goes back to normal after ~10 minutes. Not entirely clear why this is but this PR is unrelated.

Revert "Revert "feat(functions): New functions message""

---

cmd/vroom/flamegraph.go
cmd/vroom/functions.go
cmd/vroom/main.go
cmd/vroom/transaction.go
cmd/vroom/utils.go
internal/snubautil/query_builder.go

This will add the necessary IDs for rate limiting in Snuba.

feat: Add Snuba tenant IDs

---

internal/occurrence/occurrence.go

This would start sending occurrences for those new types: https://github.com/getsentry/sentry/pull/50217.

feat: Send new types of issues

---

internal/packageutil/package.go
internal/profile/android.go
internal/profile/legacy.go
internal/transaction/metadata.go

Introduces a new in app field on the android method that will be used to store the precomputed result of application vs system frame.

feat(android): Normalize android methods to contain in app

---

cmd/vroom/profile.go

When processing a profile, make the first thing we do write the profile to the storage. This means that if there's an error later in the pipeline, we will have a payload that we can use to debug the issue with.

ref(profiling): Store profile first

---

Dockerfile

I'll test this once image is built to see if it works without issues for self-hosted

Use debian bullseye in DockerFile

---

CHANGELOG.md
cmd/issuedetection/main.go
internal/occurrence/detect_frame.go
internal/occurrence/find.go
internal/occurrence/frame_drop.go
internal/occurrence/frame_drop_test.go
internal/occurrence/occurrence.go
internal/profile/legacy.go
internal/profile/profile.go
internal/sample/sample.go

This PR will find the stack likely responsible for the frozen frame drop and, if the frame drop originates from an in app function, will report an occurrence.

feat: Send occurrences on frozen frame drop

---

gocd/pipelines/cd.yaml

feat: Deploy vroom automatically on commit

---

gocd/templates/bash/deploy.sh

fix: Do not try to deploy cronjobs as vroom is a deployment

---

gocd/templates/vroom.jsonnet

feat: Deploy to S4S

---

gocd/templates/pipelines/vroom.libsonnet

fix: Remove canary stage in single tenant

---

gocd/templates/vroom.jsonnet

feat: deploy to customer-5

---

CHANGELOG.md
internal/occurrence/occurrence.go
internal/occurrence/occurrence_test.go
internal/occurrence/regressed_frame.go

In preparation for EA, support a released key that will start producing the new issue type 2011.

feat(stats-detectors): Support released key on regressed functions

---

CHANGELOG.md
cmd/vroom/main.go

chore: Disable profiling

---

.craft.yml
CHANGELOG.md

chore: Set preReleaseCommand to empty string

---

CHANGELOG.md
internal/profile/android.go
internal/profile/legacy.go

useful for react-native profiles where js profiles are converted to android ones.

keep col info when converting from android method to frame

---

.gitignore
CHANGELOG.md
cmd/vroom/profile.go
cmd/vroom/utils.go
go.mod
go.sum
internal/profile/legacy.go
internal/profile/profile.go
internal/sample/sample.go
internal/speedscope/speedscope.go
internal/utils/options.go

This PR adds support for writing function metrics into the generic metrics platform.
Support for storing profile samples will be added in a separate PR.

write function metrics to generic metrics platform

---

cloudbuild.yaml

fix: Remove cross project image push

---

cloudbuild.yaml

```
name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
```

fix: Set image tag name correctly

---

.github/workflows/ci.yaml

fix: Use new image location to pull from for Docker Hub push

---

.github/workflows/ci.yaml

https://github.com/getsentry/sentry/pull/46295#issuecomment-1482012500

chore: Remove trufflehog

---

gocd/templates/jsonnetfile.json
gocd/templates/vroom.jsonnet

feat: Add new ST environment to deploy pipeline

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json

fix: Update gocd lockfile

---

cloudbuild.yaml

ref(cloudbuild): Allow to build every branch and push only latest on main

---

internal/chunk/chunk.go

fix(chunk): Change metadata value to accept any type

---

cmd/vroom/chunk.go

add further error debug when profile chunk `unmarshal` fails

add further error debug 

---

cmd/vroom/chunk.go

ref: remove json.UnmarshalTypeError error debug

---

cmd/vroom/flamegraph.go
cmd/vroom/main.go
internal/flamegraph/span_util.go

related to https://github.com/getsentry/sentry/pull/73843

feat: add endpoint to generate a flamegraph from profile chunks

---

internal/chunk/chunk.go

this is needed to start ingesting metrics for chunks.

feat: accept DSN option in chunk

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
internal/profile/legacy.go

chore: Update gocd jsonlib to 2.13

---

CHANGELOG.md
cmd/vroom/flamegraph.go
internal/flamegraph/flamegraph.go

To get some more visibility into the code, instrument the flamegraph generation with more spans.

chore(profiling): Instrument flamegraph generation with spans

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/chunk_test.go
cmd/vroom/utils.go
internal/chunk/android.go
internal/chunk/chunk.go
internal/chunk/sample.go
internal/chunk/sample_readjob.go
internal/chunk/sample_test.go
internal/chunk/sample_utils.go
internal/chunk/sample_utils_test.go

This doesn't support:
- generating flamegraphs
- extracting metrics

feat: Ingest Android profile chunks

---

cmd/vroom/chunk_test.go

Add integration test for android chunks to ensure that we are indeed storing and fetching them properly.

add android post integration test

---

cmd/vroom/profile.go

fix: Do not report context canceled errors to Sentry

---

go.mod
go.sum

Bump sentry-go to v0.31.0

---

internal/chunk/android_utils.go
internal/chunk/android_utils_test.go

fix speedscope durationNs for android chunks

---

cmd/vroom/chunk.go

ref: add short error message to bad request response

---

internal/chunk/android_utils.go
internal/chunk/android_utils_test.go

set the platform when generating speedscope from android chunks

---

cmd/vroom/config.go
cmd/vroom/profile.go

ref: remove unused snuba_host config

---

README.md

fix broken release link

---

cmd/vroom/chunk.go
cmd/vroom/main.go

This adds an endpoint meant to be used for debug purposes.
This we'll let us the raw chunk.

feat: add internal endpoint to download a raw chunk
