getsentry/vroom

internal/occurrence/detect_frame.go
internal/occurrence/detect_frame_test.go

We can't rely on functions with a low sample count to determine if they were too long or not since maybe we didn't sample well enough. Based on a quick analysis of the current occurrences, we detect a lot of noise when looking at functions with less than 4 samples.
This will exclude them from being reported moving forward.

feat: Filter occurrences under 4 samples to increase quality

---

.github/workflows/codeql.yml

This is a basic CodeQL configuration to scan both Go and Python code in this repo.
It will run on PRs targeting main, the main branch, and weekly on the main branch.

basic codeql configuration

---

internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go

Some of the inner workings of our flamegraph components depend on the profile metadata, specifically the `projectID`. I realize we can't handle all the attributes since we're dealing with an aggregate

feat: add projectID to flamegraph

---

cmd/vroom/profile.go

This will drop the profile if the Kafka messages we're trying to produce are too big.
We'll also add to the context of the transaction the size of the profile we processed.

ref: Drop profile is the Kafka messages produced are too big

---

internal/flamegraph/flamegraph.go
internal/frame/frame.go
internal/frame/frame_test.go
internal/nodetree/nodetree.go
internal/nodetree/nodetree_test.go
internal/sample/sample.go
internal/sample/sample_test.go

Package should only be used for native platforms like cocoa and rust. This only updates it on the frame and not the nodetree because the nodetree is serialized for the suspect functions feature which coalesces module and package together still so that is left untouched. This also ensures that the frame fingerprint does not change.

fix(profiling): Do not update package on any platform

---

internal/profile/android.go
internal/profile/ios.go
internal/profile/legacy.go
internal/profile/trace.go

This also fixes the duration of the profile by calculating the delta between last and first event.

fix: Close remaining open frames for Android call trees

---

internal/flamegraph/flamegraph.go

Fixes nil pointer dereference when setting IsApplication field in Flamegraph's `visitCalltree` method.

fix: avoid nil pointer dereference

---

internal/occurrence/occurrence.go
internal/profile/legacy.go
internal/profile/profile.go
internal/sample/sample.go
internal/speedscope/speedscope.go
internal/transaction/metadata.go

We're going to start receiving transaction tags and metadata added in Relay when the profile is bundled with the transaction. This is so we can read and use them in `vroom`.

feat: Add transaction metadata and tags to the profile

---

internal/profile/ios.go

This was breaking as soon as it saw a sample from another thread other than the idle thread that's currently being filled in. This resulted in a O(n^2) runtime instead of desired O(n).

perf(ios): Correctly fill in idle stacks until next sample

---

cmd/downloader/README.md
cmd/downloader/main.go

* adds a readme on how to use the downloader script plus
* updates the bucket name hardcoded in the script which is now `sentryio-profiles`

doc: document downloader script

---

.craft.yml

We don't push an artifact when releasing, so we need to tell craft to not try to fetch one.

fix: Tell craft to not fetch an artifact for this project

---

internal/occurrence/occurrence.go

This would be paired with some frontend changes to display the profile issue template instead of performance without having to look at the issue category so we can merge everything under performance issue category.

feat: Pass a template name to render the performance issue as a profile issue

---

cmd/vroom/flamegraph.go
cmd/vroom/main.go

Instead of querying snuba for a list of profiles ID, we'll be receiving a list of `profiles_id` directly from `sentry`.
I'm turning this into a `POST` endpoint as we'll be getting a list of profiles id plus (in the near future) an optional list (for each profile id) of span data (start, end) so URL parameters might not be ideal.
Once the `sentry` change will be deployed too, I'll open another PR to remove the unused code/endpoint.

ref: receive a list of profiles ID for flamegraph generation

---

internal/nodetree/nodetree.go
internal/nodetree/nodetree_test.go

It's not super useful to show the main function in suspect function for cocoa. Remove it from aggregation.

feat(functions): Filter out cocoa main function

---

internal/flamegraph/span_util.go
internal/flamegraph/span_util_test.go

In some cases the sampling frequency is not respected.
This is particularly true for php, where the gap between two samples could be up to 30s and for Python, in case there is some native code that is holding the GIL.
This aim at mitigating (not fixing) the potential error estimating sample counts in such scenario.
The idea is that the sample count estimated for a node given a certain interval that overlaps it, should never be more than the original sample count.
So, for example, given a node with a total duration of `30s` but a sample count of `2`, if there is an interval that overlaps for the whole `30s`, instead of estimating a sample count of `3,000`, we'll set it to `2`.

mitigate sample count estimation error

---

internal/frame/frame.go
internal/frame/frame_test.go

The main function in cocoa runs for the entirety of the application and is not responsible for application code. So even though it exists in the application path, we're explicitly gmarking it as a system frame.

fix(cocoa): Special case main as system frame

---

internal/sample/sample.go

In case a bad profile makes it through, we should check that the stack ids and frame ids are valid before accessing them.

fix(call-trees): Check stack and frame id exists

---

CHANGELOG.md
internal/occurrence/occurrence.go

We're releasing the Regex issue type and we need to switch to the new type: https://github.com/getsentry/sentry/pull/52045.

feat: Release Regex issue type

---

CHANGELOG.md
cloudbuild.yaml

In order to match our Cloud Build trigger Terraform definition (https://github.com/getsentry/ops/blob/aaeac7887799595140b81da5e7cd215a94eafee9/terraform/internal-sentry/vroom/trigger.tf), we would need to embed some steps to build the Docker image directly in the Terraform definition.
I don't want to do this as it's more flexible to have the Cloud Build configuration in the service repository so we're re-introducing a Cloud Build config file which matches the existing Terraform definition.

feat: Reintroduce a Cloud Build configuration

---

.github/workflows/changelog.yaml
.github/workflows/ci.yml
CHANGELOG.md

The changelog workflow needs to check a PR contains a specific link and we won't have this on the `main` branch.

fix: Run changelog CI action only on pull requests

---

CHANGELOG.md
internal/flamegraph/flamegraph_test.go
internal/sample/sample.go
internal/sample/sample_test.go

Currently, we're look at the previous timestamp to calculate the duration of a function. The frontend is doing the opposite and is looking at the next timestamp.
During various debates, we've decided to look at the next timestamp. This PR aligns with this decision.

fix: Look forward instead of backwards when generating a call tree

---

CHANGELOG.md
internal/occurrence/detect_frame.go
internal/occurrence/detect_frame_test.go

When the signature was deobfuscated, it broke android issues detection because function name now contains the fully deobfuscated symbol names. To handle this, we're loosening the condition to match on just the function name while ignoring the argument and return types.

fix(android): Ignore arg and return types for android issues

---

CHANGELOG.md
internal/occurrence/frame_drop.go
internal/occurrence/frame_drop_test.go

Frame draps are supposed to happened at the beginning of the frozen frame and covering a good portion of the duration of the frozen frame. In this PR, I added 2 filters to weed out bad candidates and loosened when the start and end of the frame drop cause can be.
Now we'll make sure the cause is:
- within the first 20% of the frozen frame
- at least 50% of the frozen frame duration
- contained inside the frozen frame with a 5% margin at the start and end
- an application frame

feat: Filter frame drop candidates based on thresholds

---

gocd/pipelines/cd.yaml

NOTE: The `for i in $(gcloud compute os-login ssh-keys list | grep -v FINGERPRINT); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done` shouldn't be needed after it's run once and cleared out any old ssh keys.

Temp fix and switch to tunnel script

---

gocd/pipelines/cd.yaml

We only needed this to run once (added in https://github.com/getsentry/vroom/pull/309), and the issue is solved via the k8stunnel script

Remove old cleanup script

---

.github/workflows/ci.yml
CHANGELOG.md
cmd/vroom/profile.go

Following incident 501, we'll report all the GCS errors again.

fix: Report all GCS errors

---

CHANGELOG.md
cmd/vroom/main.go
go.mod
go.sum

Bump the Go SDK to [v0.24.1](https://github.com/getsentry/sentry-go/releases/tag/v0.24.1) as well as remove the `TracesSampler` in favour of using [`InboundFilters`](https://docs.sentry.io/product/data-management-settings/filtering/#transactions-coming-from-healthcheck).

Bump go sdk

---

CHANGELOG.md
internal/occurrence/frame_drop.go
internal/occurrence/frame_drop_test.go

We were not comparing the minimum duration to the duration of the frame so it was never checking for this criteria.

fix: Compare the duration of the frame to the minimum duration

---

CHANGELOG.md
cmd/vroom/main.go
cmd/vroom/regressed.go
internal/frame/frame.go
internal/frame/frame_test.go
internal/nodetree/nodetree.go
internal/occurrence/occurrence.go
internal/occurrence/regressed_frame.go

This introduces a new endpoint to create occurrences from regressed functions. When the detectors pick up a regressed function, it'll post a batch of them to this endpoint. An example will be loaded for each regression and used to fill in the details of the regression occurrence.
New group type added in getsentry/sentry#56862

feat(statistical-detectors): Add new endpoint for regressed functions

---

CHANGELOG.md
cmd/vroom/main.go

On shutdown, there will be a file at `/tmp/vroom.down`. When this file exists, it's a sign that the pod will shutdown. So return 502 from the health endpoint.

chore: Return 502 from health endpoint on shutdown

---

CHANGELOG.md
cmd/vroom/main.go

Traffic Director requires a 200 response to consider a service healthy (20X doesn't count for some reason)

fix(healthcheck): return 200 on /health ping

---

CHANGELOG.md
internal/frame/frame.go
internal/frame/frame_test.go

Sentry frames are known to be a system frame. So if they're detected, make sure they're not marked as an application frame.

fix(cocoa): Mark sentry frames as system

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
gocd/templates/vroom.jsonnet

This fixes an issue in rollbacks that can cause multiple deploys of the same commit. Now rollbacks have a final manual stage that unpauses and unlocks the pipelines once an incident is complete.
For the curious: The I removed the pipeline-complete stage in a previous version, this caused pipelines to be unlocked after a rollback is complete (a problem folks were running into), however this meant the final stage in the deploy was the stage the rollback re-ran. Since this final stage was run, it triggered the downstream pipeline to run which was unintentional.

Update GoCD library

---

CHANGELOG.md
internal/occurrence/detect_frame.go

I tried generating a JSON on Main Thread issue for the iOS SE demo app, but saw that it took a codepath through a system call we don't currently search for:

fix: add new cocoa symbol to search for for JSON issues

---

CHANGELOG.md
internal/profile/android.go
internal/profile/android_test.go
internal/profile/legacy.go

Wall-clock time is supposed to be monotonic. In a few rare cases we've noticed this was not the case.
Due to some overflow happening client-side in the embedded profiler, the sequence might be decreasing at certain points.
This is just a workaround to mitigate this issue (at rendering time) and avoid a front-end crash, should it happen.

fix: make android samples monotonic

---

.github/dependabot.yml
CHANGELOG.md
Dockerfile

- update the docker image to debian 12
- configure dependabot for all updates on docker images and github actions
Should address most of #338

deps: update docker image

---

CHANGELOG.md
cmd/vroom/profile.go
internal/storageutil/storageutil.go

We've had bugs where a profile ID would be re-used for different transactions. This would prevent the 2nd profile to be written and throw an error.

feat: Add a pre-condition to check if the file already exists before write

---

CHANGELOG.md
cmd/vroom/main.go
internal/storageutil/storageutil.go

This will use the code value as a fingerprint for all GCS errors.

feat: Return a more specific error if profile exists

---

CHANGELOG.md
internal/occurrence/occurrence.go
internal/occurrence/occurrence_test.go

The subtitle appears in the issue details but the slack previews supposedly use the important evidence display.

chore(stats-detectors): Update regression issue subtitle

---

CHANGELOG.md
internal/frame/frame.go

React-native sends mixed list of frames (Js and cocoa) with a platform field to help discern between those 2

enhance: add frame-level platform field

---

CHANGELOG.md
cmd/vroom/regressed.go

We want to start tracking which were emitted so return exactly which was emitted to make this possible.

feat(stats-detectors): Return emitted functions in response

---

CHANGELOG.md
cmd/vroom/kafka.go

Remove fields not used by the schema: https://github.com/getsentry/sentry-kafka-schemas/blob/main/schemas/profile-functions.v1.schema.json

ref(functions): Clean up Kafka message

---

gocd/templates/jsonnetfile.json
gocd/templates/jsonnetfile.lock.json
gocd/templates/vroom.jsonnet

This bumps the gocd library version so deploys go out to the `de` region as well.

feat(gocd): enable vroom deploys to DE region

---

CHANGELOG.md
internal/profile/android.go
internal/profile/android_test.go

Methods past the max stack depth should not be counted as method enters.

fix(android): Count method enters correctly

---

CHANGELOG.md
internal/profile/android.go

The enters/exits should've been counted per thread. This was working previously because the enters/exists across thread somehow added up in these bad examples, and the change to skip frames past a stack depth surfaced this issue.

fix(android): Enters/exits are per thread

---

CHANGELOG.md
cmd/vroom/config.go
cmd/vroom/kafka.go
cmd/vroom/main.go
cmd/vroom/profile.go
cmd/vroom/utils.go
internal/profile/legacy.go
internal/transaction/metadata.go
internal/transaction/transaction.go

More specifically, we'll ingest with the tags, among other things, the profile_id of the profile from which we extracted the function metric, so that we'll be able to fetch some samples when necessary.
Env. Vars. already set with PR https://github.com/getsentry/ops/pull/9698

feat: add support to ingest metric_summaries for profile functions

---

CHANGELOG.md
cmd/vroom/profile.go

This changes aim at dropping system frames when ingesting function metrics into the generic metrics platform.
Currently this would break the front-end in a few places. The logic to cap the list of functions to at most `maxUniqueFunctionsPerProfile` has therefore been moved out of the `extractFunctionsFromCallTrees` function and into a new one so that we can keep ingesting all of the frames for the current (custom) `functions` dataset, but we can start dropping them when ingesting into the generic metrics platform.
Once the front-end changes will be in place we can move this logic back to `extractFunctionsFromCallTrees` and simplify it even more.
To be merged after #441

filter out system frames when ingesting functions into generic metrics

---

CHANGELOG.md
cmd/vroom/profile.go

micro-optimization: if there are no metrics we can avoid making a call into `generateMetricSummariesKafkaMessageBatch` only to generate an empty slice that is then returned and passed to a kafka writer which in turn, has nothing to do either.

ref: skip metrics summary logic altogether if there are no metrics

---

cloudbuild.yaml

Container Registry is shutting down, we need to transition to Artifact Registry. This repository will be public and the central source to get `vroom` images for production and self-hosted.

feat: Push public images in a new Artifact Registry repo

---

CHANGELOG.md
cmd/vroom/main.go
cmd/vroom/profile.go
cmd/vroom/utils.go

We should always reuse an http client across different requests as they're thread-safe and meant to be reused for better performance (connection pooling).
This will avoid creating a new one (and relative http transport) for each and every requests we make to send metrics.
Not doing this might lead to temporary port exhaustion and degradation of perfomances.

fix: reuse one http client across different requests

---

CHANGELOG.md
internal/frame/frame.go
internal/frame/frame_test.go

with this we'll classify js frame whose function starts with `[Native]` as system frames.

fix correct in_app classification for [Native] js frames

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/config.go
cmd/vroom/main.go
cmd/vroom/profile.go
internal/chunk/chunk.go
internal/profile/legacy.go

This will store profile chunks appropriately.
https://github.com/getsentry/snuba/pull/5895

feat: Implement profile chunk storage

---

CHANGELOG.md
cmd/vroom/flamegraph.go
cmd/vroom/main.go

This was an older implementation where the profile IDs where fetched directly in vroom.
This was dismissed in favour of the next version that fetched the profile IDs in sentry and posted them to vroom, whose only task it to download and aggregate the data.
Related to https://github.com/getsentry/sentry/pull/72581

ref: remove unused flamegraph endpoint (dead code)

---

cmd/vroom/chunk.go

pass the unmarshaled chunk instead of the body request to CompressedWrite

---

cmd/vroom/chunk.go
cmd/vroom/chunk_test.go
cmd/vroom/kafka.go
cmd/vroom/main.go

ref: add postChunk integration test

---

CHANGELOG.md
internal/chunk/chunk.go

We're expecting these fields to serialize with the lower case names.

chore(chunks): Serialize chunk fields with lower case

---

CHANGELOG.md
cmd/vroom/chunk.go
internal/chunk/chunk_utils.go
internal/chunk/chunk_utils_test.go

This was returning the entire chunk all the time but we want to slice it to be between the specified start/end times.

feat(chunks): Filter out samples before start and after end

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/flamegraph.go
cmd/vroom/main.go
internal/chunk/readjob.go
internal/flamegraph/flamegraph.go
internal/storageutil/storageutil.go

The chunk task input is too specific meaning we cannot reuse the worker pool. Generalize it in preparation for using it for profiles and profile chunks.

ref(chunks): Generalize chunk task input

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/flamegraph.go
cmd/vroom/main.go
internal/chunk/readjob.go
internal/flamegraph/flamegraph.go
internal/profile/readjob.go
internal/storageutil/storageutil.go

This introduces a new endpoint that generates a flamegraph compatible with both
transaction profiles and continuous profiles.

feat(flamegraph): Dual mode flamegraph endpoint

---

CHANGELOG.md
internal/flamegraph/flamegraph.go

The channel only gets closed at the end of the function so iterating it will never terminate and just wait for the request to timeout. Since we know exactly how many values will be in the channel, iterate exactly that many times.

fix(flamegraphs): Do not iterate unclosed channel

---

CHANGELOG.md
internal/chunk/readjob.go
internal/flamegraph/flamegraph.go

This limits the calltree generated to just the selected thread for use when generating flamegraphs for a transaction/span.
Depends on getsentry/sentry#74846

feat(profiling): Pass thread id to calltree generation

---

CHANGELOG.md
internal/chunk/chunk.go
internal/chunk/chunk_test.go
internal/sample/sample.go
internal/sample/sample_test.go

There's sometimes a `<module>` frame that doesn't point to a real file but rather `<string>`. Trim it to allow better merging of profile stacks.

feat(python): Remove module frame

---

CHANGELOG.md
internal/flamegraph/span_util.go

Added in 1.21 and we run 1.22.5 in prod.

ref(vroom): Use builtin min/max functions

---

cmd/vroom/utils.go

refactor `name` to `functions` and remove `transaction`, `os_name` and `os_version`.

fix metrics tags

---

CHANGELOG.md
internal/profile/legacy.go
internal/profile/legacy_test.go

Same as https://github.com/getsentry/vroom/pull/464.
For react+android profiles though, the _js_ profile is stored as `jsonRawMessage` under a different field and we were not applying any normalization logic to that. This PR fixes it.

fix: handle js profile normalization for react+android profiles

---

CHANGELOG.md
internal/flamegraph/flamegraph.go

Forgot to pass the transaction id through to the read job so it's also annotated onto the end result.

fix(flamegraph): Pass transaction_id to chunk read job

---

CHANGELOG.md
cmd/vroom/main.go

The channel size needs to be larger than the number of items or there's a risk of the channel blocking. Will rework this a little so it starts reading immediately but starting with this for now.

chore(flamegraphs): Increase readjob channel size

---

CHANGELOG.md
internal/chunk/readjob.go
internal/flamegraph/flamegraph.go
internal/profile/readjob.go

Currently we read from gcs in a pool of workers but the calltree generation happens sequentially in the original request handler. This becomes a bottle neck as we try to generate calltrees for more profiles. So move the calltree generation into the goroutines so it happens in parallel and saturates the CPU.

perf(flamegraph): Move calltree generation into readjob

---

CHANGELOG.md
internal/profile/android.go
internal/profile/legacy.go
internal/profile/trace.go

This would use the same field for duration as https://github.com/getsentry/relay/blob/master/relay-profiling/src/android.rs#L130 which is the duration of the profile measured by the profiler https://android.googlesource.com/platform/art/+/master/runtime/trace.cc#1135.
We always set the `duration_ns` value now so I can return it directly from the metadata, not having to look through the profile.

fix: Return the duration measured by the profiler

---

CHANGELOG.md
cmd/vroom/kafka.go
cmd/vroom/profile.go

Whether we're going to store examples in `function_examples` dataset or in the existing `functions` one, we surely won't use `metrics_summary` anymore. As the profile examples data we're storing in `metrics_summary` isn't used anywhere, it's safe to be removed.

ref: stop writing profile examples to metrics_summary

---

CHANGELOG.md
internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go

Previously, we filtered out any samples that occurred less than 4 times. This results in a poor onboarding experience where if the user sends their first profile, it may not have many samples ands does not render anything on the view. This changes the logic to keep the top N samples instead to emphasize the most common stacks while not keeping infrequent ones when there are lots of others.

feat(flamegraph): Keep top N samples in flamegraph

---

CHANGELOG.md
cmd/vroom/regressed.go
internal/chunk/android.go
internal/chunk/chunk.go
internal/chunk/sample.go
internal/frame/frame.go
internal/nodetree/nodetree.go
internal/occurrence/occurrence.go
internal/occurrence/regressed_frame.go
internal/profile/android.go
internal/profile/legacy.go
internal/profile/profile.go
internal/profile/trace.go
internal/sample/sample.go

In order to support function regressions on profile chunks, we need to change from passing a simple profile id to an example metadata so we can load the chunk containing the function.

feat(statistical-detectors): Handle profile chunks in regressed endpoint

---

CHANGELOG.md
cmd/vroom/kafka.go

When writing the id to the functions table, we should be using the profiler id not the chunk id. This means all the ids before this PR are actually all wrong.

fix(profiling): Should write the profiler id

---

CHANGELOG.md
internal/profile/android.go

Whenever a frame is matched by a stack trace rule, we should prioritize the rule.
If no rule matched the frame then we can fall back on `app.identifier`.

fix: prioritize stack trace rule over app.identifier

---

CHANGELOG.md
cmd/vroom/main.go

This was causing vroom to panic during shutdowns.

chore(metrics): Remove unused metrics summary kafka writer

---

devservices/config.yml

Adding a devservices config for vroom that will enable it to be started using the new devservices that will replace the existing `sentry devservices` used today. This change should not impact how vroom is run today and is simply meant to add new functionality in the future.

feat(devservices): Adding devservices config for vroom

---

cmd/vroom/chunk.go
cmd/vroom/profile.go

These errors are already monitored and counted as a metric based on the outcome we get, we don't need them as Sentry errors.

fix: Do not report duplicate errors to Sentry

---

go.mod

As of Go 1.21, toolchain versions [must use the 1.N.P syntax](https://go.dev/doc/toolchain#version).

fix go toolchain version syntax warning

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/flamegraph.go
cmd/vroom/metrics.go
cmd/vroom/profile.go
internal/flamegraph/flamegraph.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go
internal/nodetree/nodetree.go
internal/nodetree/nodetree_test.go

This add a `minDepth` check that can be used to exclude certain frames from the function metrics aggregation.
Here it is set to `1`, meaning that we won't consider root frames while computing metrics aggregation and hence excluding such frames from the `slowest functions`.

ref: add a minDepth check for function metrics

---

CHANGELOG.md
internal/chunk/sample_readjob.go
internal/flamegraph/flamegraph.go

`CallTreesReadJob` was still using `sample` specific struct to deserialize the chunk.
With this we're going to use a `Chunk` interface and supporting `AndroidChunk` as well.

ref: use generic Chunk interface in CallTreesReadJob

---

CHANGELOG.md
internal/chunk/android.go
internal/profile/android.go

Android and sample format share the same CallTree struct. 
While the sample format (`v2`) set the `ts` of the nodes to as absolute `ts`, the android one is setting a relative one.
This break the callTree slicing.
An optional `SdkStartTime` has been added to optionally convert the `ts` to absolute ones.
For legacy android profiles we won't set it, hence it'll keep the relative ones.

fix android callTree timestamps and make them consistent with the sample (v2) format

---

.gitignore
cmd/vroom/chunk.go

Both for V2 (merged chunk) and for android (speedscope) we'll return the flamechart data under the `chunk` field.

return different flamechart data under the same chunk field

---

internal/chunk/android_utils.go
internal/chunk/android_utils_test.go
internal/speedscope/speedscope.go

Return all the measurements (V2 and legacy) under the `measurements` field (dropping _measurement_v2_) and add a `chunkID`, similarly to the `profileID` to discern between legacy profiling and continuous profiling.

ref: refactor speedscope struct

---

gocd/templates/bash/check-cloudbuild.sh

Cutting over to the new check_cloudbuild script that doesn't rely on images anymore and instead relies on repo_name, trigger_name, sha, and branch_name.
https://linear.app/getsentry/issue/DI-639/update-getsentryvroom-to-use-new-script

ref(gocd): Cutting over to check_cloudbuild.py

---

CHANGELOG.md
internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go
internal/metrics/metrics.go
internal/profile/profile.go
internal/utils/structs.go

Previously, only chunk examples had start/end associated with it. There's no reason why profile examples can't have them so make sure they're added so it can be used by the UI.

feat(flamegraph): Add start/end to profile example

---

README.md

We don't interact with `Snuba` from `vroom` anymore, so it should be removed from the list of requirements for development.

ref: remove reference to snuba in the dev requirements

---

cmd/vroom/kafka.go

Support for android chunks metrics extraction was added a few months back.
This comment is not valid anymore.

chore: remove old comment

---

CHANGELOG.md
internal/flamegraph/flamegraph.go

This buffers the profile candidates after they're read to prevent all of them being held in memory at the same time.

chore(flamegraph): Buffer flamegraph candidates to reduce memory usage

---

CHANGELOG.md
cmd/vroom/chunk.go
cmd/vroom/config.go
internal/metrics/metrics.go

Previously buffered the results on flamegraph endpoint. This makes the results a buffered channel in all places and lowers the number of workers in an attempt to lower the memory usage further.

chore(profiling): Reduce Read jobs buffer to reduce memory

---

.github/workflows/ci.yaml

Fixes https://github.com/getsentry/vroom/actions/runs/15611124623/job/43972275881
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

ci: create one manifest at a time

---

.github/workflows/ci.yaml

This was missing. Copying what relay did here: https://github.com/getsentry/relay/blob/7f4b354ebb99286dd20ee34c1da4540f7e1135bd/.github/workflows/ci.yml#L579-L594
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

ci: correctly push multiplatform image to dockerhub

---

CHANGELOG.md
internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go
internal/nodetree/nodetree.go
internal/speedscope/speedscope.go

After playing around with #622, it doesn't actually work because a single occurrence can span multiple stacks. This reverts parts of those changes and favours annotating some metadata indicating the number of calls and the duration of a frame.

feat(flamegraph): Return number of occurrences in flamegraph per frame

---

CHANGELOG.md
internal/flamegraph/flamegraph_test.go
internal/metrics/metrics.go
internal/nodetree/nodetree.go
internal/nodetree/nodetree_test.go

If the functions with 0 self time is removed immediately, it's duration won't be used to compute the metrics leading to some discrepancies.

fix(flamegraph): Remove functions with zero self time at the end

---

internal/chunk/sample_test.go
internal/flamegraph/flamegraph.go
internal/flamegraph/flamegraph_test.go
internal/nodetree/nodetree.go
internal/profile/android_test.go
internal/sample/sample_test.go
internal/speedscope/speedscope.go

Profile ids were used for transaction profiles. Since continuous profiling, we've moved to profiles where it contains metadata indicating either a transaction profile or a continuous profile.

chore(flamegraph): Remove unused profile ids from speedscope
